import { narutocharacter } from './animeСharacter/narutocharacter';
import { norogamicharacter } from './animeСharacter/norogamicharacter';
import { tokyoghoulcharacter } from './animeСharacter/tokyoghoulcharacter';

export const animetitle = [
  {
    id: 0,
    title: 'Noragami',
    studio: 'Studio',
    year: 2000,
    gender: 'meow',
    img: './img/cardanime/noragami.jpg',
    posterimg: './img/person/norogami/yato-full.png',
    characters: norogamicharacter,
  },
  {
    id: 1,
    title: 'Naruto',
    studio: 'Studio Pierrot',
    year: 2000,
    gender: 'meow',
    img: './img/cardanime/naruto.jpg',
    characters: narutocharacter,
  },
  {
    id: 2,
    title: 'Bleach',
    studio: 'Studio Pierrot',
    year: 2000,
    gender: 'meow',
    img: './img/cardanime/bleach.jpg',
  },
  {
    id: 3,
    title: 'Tokyo Ghoul',
    studio: 'Studio Pierrot',
    year: 2000,
    gender: 'meow',
    img: './img/cardanime/tokyoghole.jpg',
    characters: tokyoghoulcharacter,
  },
  {
    id: 4,
    title: 'Another',
    studio: 'P.A. Works',
    year: 2000,
    gender: 'meow',
    img: './img/cardanime/Another.jpeg',
  },
  {
    id: 5,
    title: 'Sen to Chihiro no Kamikakushi',
    studio: 'Studio Ghibli',
    year: 2000,
    gender: 'meow',
    img: './img/cardanime/SentoChihironoKamikakushi.jpg',
  },
  {
    id: 6,
    title: 'Howl no Ugoku Shiro',
    studio: 'Studio Ghibli',
    year: 2000,
    gender: 'meow',
    img: './img/cardanime/HowlnoUgokuShiro.jpg',
  },
  {
    id: 7,
    title: 'Mononoke Hime',
    studio: 'Studio Ghibli',
    year: 2000,
    gender: 'meow',
    img: './img/cardanime/MononokeHime.jpg',
  },
  {
    id: 8,
    title: 'Gake no Ue no Ponyo',
    studio: 'Studio Ghibli',
    year: 2000,
    gender: 'meow',
    img: './img/cardanime/GakenoUenoPonyo.jpg',
  },
  {
    id: 9,
    title: 'Fullmetal Alchemist: Brotherhood',
    studio: 'Bones Animation Studios',
    year: 2000,
    gender: 'meow',
    img: './img/cardanime/FullmetalAlchemistBrotherhood.jpg',
  },
  {
    id: 10,
    title: 'Demon Slayer: Kimetsu no Yaiba',
    studio: 'Ufotable',
    year: 2000,
    gender: 'meow',
    img: './img/cardanime/DemonSlayerKimetsunoYaiba.jpg',
  },
  {
    id: 11,
    title: 'Mo Dao Zu Shi',
    studio: 'Tencent Penguin Pictures',
    year: 2000,
    gender: 'meow',
    img: './img/cardanime/MoDaoZuShi.jpeg',
  },
  {
    id: 12,
    title: 'Jujutsu Kaisen',
    studio: 'Studio MAPPA',
    year: 2000,
    gender: 'meow',
    img: './img/cardanime/JujutsuKaisen.jpeg',
  },
  {
    id: 13,
    title: 'aaaaaaaaaaaa',
    studio: 'Studio',
    year: 2000,
    gender: 'meow',
    img: './img/cardanime/aaaaaaaa.aaaaaaaaaaaaa',
  },
];
